### ISSUE TITLE
bug in run() with basepath != '/' ?

### ISSUE THREAD

**Issue by marcoas** [splashsky/simplerouter#12]
(Translated by Google)

Hello
I am testing a version modified by me, of ROUTER.PHP
and when I use for example:

```
Router::add('/', function () {
   echo 'Welcome to v3';
});
Router: run('/v3');
```

I needed to modify this line in the RUN method

```
if ($basePath != '/') {
   $route['route'] = self::trimRoute($basePath. $route['route']);
}
```

Otherwise the path "/" always returned 404
This only happened with the '/' path, the others always worked fine.

Maybe it is really necessary to change it in this repository

**Comment by splashsky** [comment]
I believe I got this to work properly on commit bf6da3b9900589eda2f8ff4b7c534e7435ee9f9b - I added your fix and also corrected the constraints array issue that popped up in `tokenize()` when using a base path.

Thanks for the bug report! Let me know if this also fixes in your project and I'll close the Issue.

**Comment by marcoas** [comment]
(Translated by Google)

If exactly, I had done the same to solve it.
